### ISSUE TITLE
Define better some things in roadmap/to-do

### ISSUE THREAD

**Issue by palasso** [Gamah/gBot#34]
Describe better how we wish to implement some things e.g. "Implement !help command which dynamically handles existing commands" and "Refactor socket parsing" or try to provide more info for "Detect connection failure and reconnect" in order to try to reproduce.

Additionally as suggested in CONTRIBUTING declare in to-do a new important feature: commands module! This also needs more info.

Better provide info in new issues for each one and contributors might be able to solve some of these.

**Comment by Gamah** [comment]
I don't like the verbology of "roadmap." A todo list in the readme is enough for me. If you want to provide a compelling argument for a separate file I may consider otherwise.

As for the help command: I want a consistent method which (once properly implemented) parses the "commands" file for each existing method and builds the cmdlist object dynamically, preferably taking a property of each method in the "commands" file as a descriptor to what the function/command does as feedback to the user.

In the project's current state this might look like a "!help" command (outside of the commands class) which parses the class (in spite of the fact a lot of socket stuff should be extracted from it) and returns something like "Commands: !smug = 'Say Fuck you to a user of your choice!', !bacon = 'give a delicious strip of bacon to yourself or another patron!', !cn = 'Random chuck norris joke, specify a 1 or 2 word name!' etc etc...

**Comment by palasso** [comment]
Not suggesting separate file in this issue (was a mention in issue #30 ) (also won't use again the term roadmap), just creating issues with more details on some of them. In your comment you already described !help. I will implement for starters something for !help without taking into consideration the commands module and it can be the basis for when the commands module will be implemented.

Any more details on "Refactor socket parsing"? If you can describe how to reproduce (or provide any details) the bug that hangs gbot would be a starting point for me.

**Comment by Gamah** [comment]
Right now the code makes some very ircd-specific assumptions (of which I have seen issues on other networks vs geekshed) that are not completely RFC-spec sane.

I should (need to) spend some time reworking the fundamentals of how the "info" object is built (user/sender/command/message/botcmd/etc) to handle it in a much safer/sane way. I'd also like the botcmd prefix to be arbitrary vs the current hard coded "!"

As for the bug that currently hangs gbot in my active channel. I haven't done any research. My assumption is it's to do with URL parsing and may have been fixed with your recent PR. Again, haven't bothered to dig in to it.

**Comment by Gamah** [comment]
Closing this, the current roadmap is fuzzy at best. This isn't a project I take immensely seriously and I do not wish for it to become so.

While it's functional, any actual programmers looking to implement an IRC bot ought to use existing libraries.

**Comment by palasso** [comment]
Ok, I suggest resorting in to-do the to-do's in the order that can be started, so !help should be beneath commands module and commands module should be beneath refactoring socket handling.

So currently I'd say the to-do is:
- Remove dependency on external requests module, do all HTTP things with urllib (DONE when my PR gets merged)
- Detect connection failure and reconnect
- Refactor socket parsing
- Implement commands module
- Implement !help command which dynamically handles commands from commands module
- A lot of other stuff...

How about we create one issue on discussing "to-do's" and leave it permanently open? Could be called like "Development-Next" or "To-Do Discussion".
