### ISSUE TITLE
Request timeout does not take a tuple

### ISSUE THREAD

**Issue by Gamah** [Gamah/gBot#36]
Commit: 5481927733157bfab8a4694d5b7055289658a0ec
This threw an exception for every URL and stopped gbot from returning page titles.

**Comment by palasso** [comment]
According to [documentation](http://docs.python-requests.org/en/latest/user/advanced/#timeouts) timeout can be both a number and a tuple. When it's a tuple first number is connect timeout, second number is read timeout (it makes sense to want to be more relaxed in timeout time for read (for big pages) in relation to just connect timeout). When it's a number then connect and read timeouts are the same. I've tested it multiple times but could not reproduce the aforementioned bug. I suspect the problem was elsewhere. Unless gbot production system runs a version of requests older than [2.4](https://pypi.python.org/pypi/requests/). It can be checked with `pip freeze | grep requests`.
